/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecipeResultRouteImport } from './routes/recipe-result'
import { Route as OutChatRouteImport } from './routes/out-chat'
import { Route as NaverCallbackRouteImport } from './routes/naver-callback'
import { Route as MypageRouteImport } from './routes/mypage'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CookStartRouteImport } from './routes/cook-start'
import { Route as CookCompleteRouteImport } from './routes/cook-complete'
import { Route as CookAudioRouteImport } from './routes/cook-audio'
import { Route as CookRouteImport } from './routes/cook'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes.index'
import { Route as RecipesMyRouteImport } from './routes/recipes.my'

const RecipeResultRoute = RecipeResultRouteImport.update({
  id: '/recipe-result',
  path: '/recipe-result',
  getParentRoute: () => rootRouteImport,
} as any)
const OutChatRoute = OutChatRouteImport.update({
  id: '/out-chat',
  path: '/out-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const NaverCallbackRoute = NaverCallbackRouteImport.update({
  id: '/naver-callback',
  path: '/naver-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageRoute = MypageRouteImport.update({
  id: '/mypage',
  path: '/mypage',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CookStartRoute = CookStartRouteImport.update({
  id: '/cook-start',
  path: '/cook-start',
  getParentRoute: () => rootRouteImport,
} as any)
const CookCompleteRoute = CookCompleteRouteImport.update({
  id: '/cook-complete',
  path: '/cook-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const CookAudioRoute = CookAudioRouteImport.update({
  id: '/cook-audio',
  path: '/cook-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const CookRoute = CookRouteImport.update({
  id: '/cook',
  path: '/cook',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesMyRoute = RecipesMyRouteImport.update({
  id: '/recipes/my',
  path: '/recipes/my',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/cook': typeof CookRoute
  '/cook-audio': typeof CookAudioRoute
  '/cook-complete': typeof CookCompleteRoute
  '/cook-start': typeof CookStartRoute
  '/home': typeof HomeRoute
  '/loading': typeof LoadingRoute
  '/mypage': typeof MypageRoute
  '/naver-callback': typeof NaverCallbackRoute
  '/out-chat': typeof OutChatRoute
  '/recipe-result': typeof RecipeResultRoute
  '/recipes/my': typeof RecipesMyRoute
  '/recipes/': typeof RecipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/cook': typeof CookRoute
  '/cook-audio': typeof CookAudioRoute
  '/cook-complete': typeof CookCompleteRoute
  '/cook-start': typeof CookStartRoute
  '/home': typeof HomeRoute
  '/loading': typeof LoadingRoute
  '/mypage': typeof MypageRoute
  '/naver-callback': typeof NaverCallbackRoute
  '/out-chat': typeof OutChatRoute
  '/recipe-result': typeof RecipeResultRoute
  '/recipes/my': typeof RecipesMyRoute
  '/recipes': typeof RecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/cook': typeof CookRoute
  '/cook-audio': typeof CookAudioRoute
  '/cook-complete': typeof CookCompleteRoute
  '/cook-start': typeof CookStartRoute
  '/home': typeof HomeRoute
  '/loading': typeof LoadingRoute
  '/mypage': typeof MypageRoute
  '/naver-callback': typeof NaverCallbackRoute
  '/out-chat': typeof OutChatRoute
  '/recipe-result': typeof RecipeResultRoute
  '/recipes/my': typeof RecipesMyRoute
  '/recipes/': typeof RecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/cook'
    | '/cook-audio'
    | '/cook-complete'
    | '/cook-start'
    | '/home'
    | '/loading'
    | '/mypage'
    | '/naver-callback'
    | '/out-chat'
    | '/recipe-result'
    | '/recipes/my'
    | '/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/cook'
    | '/cook-audio'
    | '/cook-complete'
    | '/cook-start'
    | '/home'
    | '/loading'
    | '/mypage'
    | '/naver-callback'
    | '/out-chat'
    | '/recipe-result'
    | '/recipes/my'
    | '/recipes'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/cook'
    | '/cook-audio'
    | '/cook-complete'
    | '/cook-start'
    | '/home'
    | '/loading'
    | '/mypage'
    | '/naver-callback'
    | '/out-chat'
    | '/recipe-result'
    | '/recipes/my'
    | '/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  CookRoute: typeof CookRoute
  CookAudioRoute: typeof CookAudioRoute
  CookCompleteRoute: typeof CookCompleteRoute
  CookStartRoute: typeof CookStartRoute
  HomeRoute: typeof HomeRoute
  LoadingRoute: typeof LoadingRoute
  MypageRoute: typeof MypageRoute
  NaverCallbackRoute: typeof NaverCallbackRoute
  OutChatRoute: typeof OutChatRoute
  RecipeResultRoute: typeof RecipeResultRoute
  RecipesMyRoute: typeof RecipesMyRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recipe-result': {
      id: '/recipe-result'
      path: '/recipe-result'
      fullPath: '/recipe-result'
      preLoaderRoute: typeof RecipeResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/out-chat': {
      id: '/out-chat'
      path: '/out-chat'
      fullPath: '/out-chat'
      preLoaderRoute: typeof OutChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/naver-callback': {
      id: '/naver-callback'
      path: '/naver-callback'
      fullPath: '/naver-callback'
      preLoaderRoute: typeof NaverCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage': {
      id: '/mypage'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof MypageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cook-start': {
      id: '/cook-start'
      path: '/cook-start'
      fullPath: '/cook-start'
      preLoaderRoute: typeof CookStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cook-complete': {
      id: '/cook-complete'
      path: '/cook-complete'
      fullPath: '/cook-complete'
      preLoaderRoute: typeof CookCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cook-audio': {
      id: '/cook-audio'
      path: '/cook-audio'
      fullPath: '/cook-audio'
      preLoaderRoute: typeof CookAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cook': {
      id: '/cook'
      path: '/cook'
      fullPath: '/cook'
      preLoaderRoute: typeof CookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/my': {
      id: '/recipes/my'
      path: '/recipes/my'
      fullPath: '/recipes/my'
      preLoaderRoute: typeof RecipesMyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CookRoute: CookRoute,
  CookAudioRoute: CookAudioRoute,
  CookCompleteRoute: CookCompleteRoute,
  CookStartRoute: CookStartRoute,
  HomeRoute: HomeRoute,
  LoadingRoute: LoadingRoute,
  MypageRoute: MypageRoute,
  NaverCallbackRoute: NaverCallbackRoute,
  OutChatRoute: OutChatRoute,
  RecipeResultRoute: RecipeResultRoute,
  RecipesMyRoute: RecipesMyRoute,
  RecipesIndexRoute: RecipesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
